typography_spectrum: 0.9422678811144599
color:
  brandStrength: 0.01298136822639568
  saturation: 0.49004954652464255
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  lightness: 0.37729778732892383
  rhythmicContrast: 0.09717861272652845
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21179795807891405
analytics:
  twitter: null
  google: null
  facebook: null
name: Nederlandse-Webwinkels
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - name: test
    id: cb11338f-ffc2-4a91-9ef9-7d48634cc038
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Nederlandse Webwinkels
content: []
description: ''
purpose: []
