typography_spectrum: 0.9422678811144599
color:
  brandStrength: 0.01298136822639568
  saturation: 0.49004954652464255
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  lightness: 0.37729778732892383
  rhythmicContrast: 0.09717861272652845
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21179795807891405
analytics:
  twitter: null
  google: null
  facebook: null
name: Nederlandse-Webwinkels
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - name: Software
    id: 9fe5b614-baa9-4ca2-8abc-0727747b2bcb
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Nederlandse Webwinkels
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/cb6afba6-b790-4583-ade8-a059d1409250.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/cb6afba6-b790-4583-ade8-a059d1409250.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
